import Link from "next/link";

const contact = process.env.NEXT_PUBLIC_LEGAL_CONTACT_EMAIL;
export const metadata = { title: "Privacy | First Day" };

export default function PrivacyPage() {
  return <main className="min-h-screen bg-white px-5 py-14 sm:px-8"><article className="surface-card mx-auto max-w-3xl p-7 sm:p-10">
    <Link href="/" className="text-sm font-medium text-indigo-700 hover:text-indigo-900">← Back to First Day</Link>
    <p className="mt-8 text-xs font-semibold uppercase tracking-[0.18em] text-indigo-600">First Day</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">Privacy notice</h1><p className="mt-3 text-sm text-slate-500">Last updated: July 16, 2026</p>
    <div className="mt-8 space-y-7 text-sm leading-6 text-slate-700">
      <section><h2 className="text-lg font-semibold text-slate-900">What we process</h2><p className="mt-2">First Day stores an anonymous browser identifier, subject titles, optional notes, chat messages, onboarding progress, reports, and generated new-hire content. If you upload a document, extracted text is used to prepare the onboarding map. It is removed when preparation succeeds; a failed draft retains it only until you retry or delete that draft. We retain only limited file metadata: type and extracted character count.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Why we process it</h2><p className="mt-2">We use this information to provide your private onboarding desk, run the conversation, save progress, generate reports, protect the service against misuse, and support reusable shared onboarding templates. Processing is necessary to provide the service you request and to keep it secure.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Service providers and AI</h2><p className="mt-2">We use Vercel to host the application, Neon to store application data, and OpenAI&apos;s API to generate learning maps, study-partner replies, and reports. Relevant subject material and messages are sent to OpenAI when needed for these features. Learning-map generation runs as a short background job so it can be polled; OpenAI temporarily retains that job data for this purpose. OpenAI states that API inputs and outputs are not used to train its models by default; its abuse-monitoring logs may be retained for a limited period.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Do not upload sensitive material</h2><p className="mt-2">Only upload material you are authorised to use. Do not upload personal, confidential, regulated, or security-sensitive information unless you have assessed and approved the use of each provider for that material.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Sharing</h2><p className="mt-2">A shared-learning link is a bearer link: anyone who has it can open the shared template and create their own private copy. Do not share a link if the subject title, template, or colleague setup is confidential.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Retention and deletion</h2><p className="mt-2">Onboarding data remains in your private onboarding desk until you delete an individual onboarding plan or choose <strong>Delete my data</strong> from the onboarding desk. Deleting your data removes your subjects, chats, reports, progress, and anonymous mentor record from the active application database. Limited backups and provider logs may persist for their normal retention periods.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Cookies and browser storage</h2><p className="mt-2">First Day uses a strictly necessary, HTTP-only session cookie and local browser storage to keep your anonymous onboarding desk private. It does not use advertising cookies. If analytics or marketing trackers are added, this notice and consent controls will be updated before they are used.</p></section>
      <section><h2 className="text-lg font-semibold text-slate-900">Your rights and contact</h2><p className="mt-2">Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or receive your personal data, and to complain to your supervisory authority. {contact ? <>Contact the publisher at <a className="font-medium text-indigo-700 underline" href={`mailto:${contact}`}>{contact}</a>.</> : <>The publisher must configure a public privacy contact before launching this service.</>}</p></section>
    </div>
  </article></main>;
}
