"use client";

import { useState } from "react";

type Result = { conceptId: string; concept: string; question: string; answer: string; correct: boolean };
type Check = { hireName: string; questions: Result[]; score: number; passed: boolean; failed: Array<{ conceptId: string; concept: string }>; tier: string };

export default function TrialView({ subjectId }: { subjectId?: string }) {
  const [check, setCheck] = useState<Check>(); const [index, setIndex] = useState(0); const [running, setRunning] = useState(false); const [error, setError] = useState<string>();
  async function start() { if (!subjectId) { setError("Open this page from a learning path to run a knowledge check."); return; } setRunning(true); setError(undefined); setIndex(0); try { const response = await fetch("/api/trial", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subjectId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to start the knowledge check."); setCheck(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to start the knowledge check."); } finally { setRunning(false); } }
  const current = check?.questions[index]; const finished = check && index >= check.questions.length;
  return <main className="min-h-screen bg-white px-5 py-14 text-slate-800 sm:px-8 sm:py-20"><div className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-600">First Day · Knowledge check</p><h1 className="font-display mt-4 text-4xl font-semibold tracking-[-0.03em] text-[#111827] sm:text-5xl">Watch your learning partner apply the ideas</h1><p className="mt-4 text-slate-600">This short check shows what has really clicked so far.</p>{!check ? <div className="surface-card mt-10 p-7"><p className="text-sm text-slate-600">The check draws from concepts you have already explored.</p><button onClick={start} disabled={running} className="button-primary mt-5">{running ? "Preparing check..." : "Start knowledge check"}</button>{error ? <p className="mt-3 text-sm text-rose-600">{error}</p> : null}</div> : null}{current ? <section className="surface-card mt-10 p-7"><p className="text-sm font-medium text-indigo-600">Question {index + 1} of {check.questions.length} · {current.concept}</p><h2 className="font-display mt-4 text-3xl font-semibold leading-10 text-[#111827]">{current.question}</h2><div className="mt-7 rounded-2xl border border-[#F3F4F6] bg-[#F9FAFB] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">{check.hireName}&apos;s answer</p><p className="mt-3 text-sm leading-7 text-slate-700">{current.answer}</p></div><button onClick={() => setIndex((value) => value + 1)} className="button-primary mt-6">{index + 1 === check.questions.length ? "See results" : "Next"}</button></section> : null}{finished ? <section className="surface-card mt-10 p-7"><p className="text-sm font-semibold text-indigo-600">Knowledge check complete</p><h2 className="font-display mt-2 text-5xl font-semibold text-[#111827]">{check.score}%</h2><p className="mt-3 text-slate-600">Your learning partner only knows what you explained clearly.</p><p className={`mt-5 rounded-xl px-4 py-3 text-sm font-semibold ${check.passed ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{check.passed ? `${check.tier} is unlocked.` : "A few ideas need another pass."}</p>{check.failed.length ? <div className="mt-7"><h3 className="font-semibold text-slate-900">Ideas to revisit</h3><ul className="mt-3 space-y-2">{check.failed.map((item) => <li key={item.conceptId} className="rounded-xl bg-[#F9FAFB] px-4 py-3 text-sm text-slate-700">{item.concept}</li>)}</ul></div> : null}</section> : null}</div></main>;
}
